export const siteUrl = "https://theodoredits.com";

export const siteName = "Theodor Videography";

export const defaultTitle =
  "Freelance Videographer & Remote Video Editor | Corporate, Brand & Commercial Video Production";

export const defaultDescription =
  "End-to-end video production for brands, agencies, and businesses worldwide. From pre-production and filming to editing, colour grading, and final delivery. Available for remote and on-location projects.";

export const keywords = [
  "Videographer",
  "Video Editor",
  "Freelance Videographer",
  "Freelance Video Editor",
  "Remote Video Editor",
  "Remote Videographer",
  "Commercial Videographer",
  "Corporate Video Production",
  "Video Production",
  "Video Production Services",
  "End-to-End Video Production",
  "Cinematic Video Production",
  "Corporate Video",
  "Brand Films",
  "Promotional Videos",
  "Marketing Videos",
  "Social Media Videos",
  "Testimonial Videos",
  "Event Videography",
  "Documentary Style Video",
  "Product Videos",
  "Interview Videos",
  "Short-form Video Editing",
  "Long-form Video Editing",
  "Vertical Video Editing",
  "YouTube Video Editing",
  "Commercial Editing",
  "Colour Grading",
  "Motion Graphics",
  "Subtitling",
  "Post-Production",
  "Remote Video Production",
  "International Video Production",
  "Freelance Creative",
  "Remote Creative Services",
  "Global Video Production",
  "Overseas Video Production",
  "Project-Based Videographer",
  "Contract Video Editor",
  "Remote Content Creator",
  "FinTech Video Production",
  "Corporate Communications",
  "B2B Video Production",
  "Startup Video Production",
  "NGO Video Production",
  "Educational Videos",
  "Event Marketing",
  "Employer Branding",
  "Customer Testimonial Videos",
  "Product Launch Videos",
  "Adobe Premiere Pro",
  "DaVinci Resolve",
  "Video Editing",
  "Videography",
  "Storytelling",
  "Cinematography",
  "Creative Direction",
  "Production Planning",
  "Pre-production",
  "Filming",
  "Audio Editing",
  "Colour Correction",
  "Content Strategy",
  "Romania Videographer",
  "Romanian Video Editor",
  "European Video Production",
  "Europe-based Video Editor",
  "EU Freelance Videographer",
  "Available Worldwide",
];

export const portfolioTags = [
  "Videographer",
  "Video Editor",
  "Video Production",
  "Corporate Video",
  "Brand Film",
  "Commercial",
  "Documentary",
  "Promotional Video",
  "Event Video",
  "Testimonial",
  "Interview",
  "Marketing",
  "Social Media",
  "Remote",
  "Freelance",
  "Premiere Pro",
  "Colour Grading",
  "Storytelling",
];
